/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AgentGraph: typeof import('./components/AgentGraph.vue')['default']
    ChatCopilot: typeof import('./components/ChatCopilot.vue')['default']
    DailySummaryCard: typeof import('./components/DailySummaryCard.vue')['default']
    DebatePanel: typeof import('./components/DebatePanel.vue')['default']
    DecisionCard: typeof import('./components/DecisionCard.vue')['default']
    ElAlert: typeof import('element-plus/es')['ElAlert']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElCollapse: typeof import('element-plus/es')['ElCollapse']
    ElCollapseItem: typeof import('element-plus/es')['ElCollapseItem']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDescriptions: typeof import('element-plus/es')['ElDescriptions']
    ElDescriptionsItem: typeof import('element-plus/es')['ElDescriptionsItem']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElLink: typeof import('element-plus/es')['ElLink']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElProgress: typeof import('element-plus/es')['ElProgress']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    KlineChart: typeof import('./components/KlineChart.vue')['default']
    MarketOverview: typeof import('./components/MarketOverview.vue')['default']
    MarketRegimeCard: typeof import('./components/MarketRegimeCard.vue')['default']
    MetricCardGrid: typeof import('./components/MetricCardGrid.vue')['default']
    PortfolioSummary: typeof import('./components/PortfolioSummary.vue')['default']
    ReportRenderer: typeof import('./components/ReportRenderer.vue')['default']
    ReportViewer: typeof import('./components/ReportViewer.vue')['default']
    RiskItems: typeof import('./components/RiskItems.vue')['default']
    RiskMonitor: typeof import('./components/RiskMonitor.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScreeningStageCard: typeof import('./components/ScreeningStageCard.vue')['default']
    StockAnalysis: typeof import('./components/StockAnalysis.vue')['default']
    StockDetail: typeof import('./components/StockDetail.vue')['default']
    TaskProgressBanner: typeof import('./components/TaskProgressBanner.vue')['default']
    TradingSignals: typeof import('./components/TradingSignals.vue')['default']
  }
  export interface GlobalDirectives {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
